//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.ServiciosAhorcado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class JugadorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeNacimiento {
            get {
                return this.FechaDeNacimientoField;
            }
            set {
                if ((this.FechaDeNacimientoField.Equals(value) != true)) {
                    this.FechaDeNacimientoField = value;
                    this.RaisePropertyChanged("FechaDeNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class CategoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreInglesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles {
            get {
                return this.NombreInglesField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreInglesField, value) != true)) {
                    this.NombreInglesField = value;
                    this.RaisePropertyChanged("NombreIngles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DificultadDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class DificultadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreInglesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles {
            get {
                return this.NombreInglesField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreInglesField, value) != true)) {
                    this.NombreInglesField = value;
                    this.RaisePropertyChanged("NombreIngles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PalabraDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class PalabraDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionInglesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDificultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreInglesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionIngles {
            get {
                return this.DescripcionInglesField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionInglesField, value) != true)) {
                    this.DescripcionInglesField = value;
                    this.RaisePropertyChanged("DescripcionIngles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDificultad {
            get {
                return this.IdDificultadField;
            }
            set {
                if ((this.IdDificultadField.Equals(value) != true)) {
                    this.IdDificultadField = value;
                    this.RaisePropertyChanged("IdDificultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles {
            get {
                return this.NombreInglesField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreInglesField, value) != true)) {
                    this.NombreInglesField = value;
                    this.RaisePropertyChanged("NombreIngles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaDisponibleDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class PartidaDisponibleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorAnfitrionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDificultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAnfitrionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugadorAnfitrion {
            get {
                return this.IdJugadorAnfitrionField;
            }
            set {
                if ((this.IdJugadorAnfitrionField.Equals(value) != true)) {
                    this.IdJugadorAnfitrionField = value;
                    this.RaisePropertyChanged("IdJugadorAnfitrion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPartida {
            get {
                return this.IdPartidaField;
            }
            set {
                if ((this.IdPartidaField.Equals(value) != true)) {
                    this.IdPartidaField = value;
                    this.RaisePropertyChanged("IdPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idioma {
            get {
                return this.IdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdiomaField, value) != true)) {
                    this.IdiomaField = value;
                    this.RaisePropertyChanged("Idioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCategoria {
            get {
                return this.NombreCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCategoriaField, value) != true)) {
                    this.NombreCategoriaField = value;
                    this.RaisePropertyChanged("NombreCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDificultad {
            get {
                return this.NombreDificultadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDificultadField, value) != true)) {
                    this.NombreDificultadField = value;
                    this.RaisePropertyChanged("NombreDificultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePalabra {
            get {
                return this.NombrePalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePalabraField, value) != true)) {
                    this.NombrePalabraField = value;
                    this.RaisePropertyChanged("NombrePalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioAnfitrion {
            get {
                return this.UsuarioAnfitrionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAnfitrionField, value) != true)) {
                    this.UsuarioAnfitrionField = value;
                    this.RaisePropertyChanged("UsuarioAnfitrion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialPartidaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Dtos")]
    [System.SerializableAttribute()]
    public partial class HistorialPartidaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DificultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dificultad {
            get {
                return this.DificultadField;
            }
            set {
                if ((object.ReferenceEquals(this.DificultadField, value) != true)) {
                    this.DificultadField = value;
                    this.RaisePropertyChanged("Dificultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosAhorcado.IGestorPrincipal", CallbackContract=typeof(AhorcadoCliente.ServiciosAhorcado.IGestorPrincipalCallback))]
    public interface IGestorPrincipal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/RegistrarJugador", ReplyAction="http://tempuri.org/IJugadorManager/RegistrarJugadorResponse")]
        int RegistrarJugador(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/RegistrarJugador", ReplyAction="http://tempuri.org/IJugadorManager/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<int> RegistrarJugadorAsync(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/ActualizarJugador", ReplyAction="http://tempuri.org/IJugadorManager/ActualizarJugadorResponse")]
        int ActualizarJugador(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/ActualizarJugador", ReplyAction="http://tempuri.org/IJugadorManager/ActualizarJugadorResponse")]
        System.Threading.Tasks.Task<int> ActualizarJugadorAsync(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/EliminarJugador", ReplyAction="http://tempuri.org/IJugadorManager/EliminarJugadorResponse")]
        int EliminarJugador(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/EliminarJugador", ReplyAction="http://tempuri.org/IJugadorManager/EliminarJugadorResponse")]
        System.Threading.Tasks.Task<int> EliminarJugadorAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/ObtenerTodosLosJugadores", ReplyAction="http://tempuri.org/IJugadorManager/ObtenerTodosLosJugadoresResponse")]
        AhorcadoCliente.ServiciosAhorcado.JugadorDTO[] ObtenerTodosLosJugadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorManager/ObtenerTodosLosJugadores", ReplyAction="http://tempuri.org/IJugadorManager/ObtenerTodosLosJugadoresResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.JugadorDTO[]> ObtenerTodosLosJugadoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISesionManager/IniciarSesion", ReplyAction="http://tempuri.org/ISesionManager/IniciarSesionResponse")]
        AhorcadoCliente.ServiciosAhorcado.JugadorDTO IniciarSesion(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISesionManager/IniciarSesion", ReplyAction="http://tempuri.org/ISesionManager/IniciarSesionResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.JugadorDTO> IniciarSesionAsync(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerCategorias", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerCategoriasResponse")]
        AhorcadoCliente.ServiciosAhorcado.CategoriaDTO[] ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerCategorias", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerCategoriasResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.CategoriaDTO[]> ObtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerDificultades", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerDificultadesResponse")]
        AhorcadoCliente.ServiciosAhorcado.DificultadDTO[] ObtenerDificultades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerDificultades", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerDificultadesResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.DificultadDTO[]> ObtenerDificultadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerPalabrasPorCategoriaYDificultad", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerPalabrasPorCategoriaYDificultadResponse" +
            "")]
        AhorcadoCliente.ServiciosAhorcado.PalabraDTO[] ObtenerPalabrasPorCategoriaYDificultad(int idCategoria, int idDificultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraManager/ObtenerPalabrasPorCategoriaYDificultad", ReplyAction="http://tempuri.org/IPalabraManager/ObtenerPalabrasPorCategoriaYDificultadResponse" +
            "")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.PalabraDTO[]> ObtenerPalabrasPorCategoriaYDificultadAsync(int idCategoria, int idDificultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/CrearPartida", ReplyAction="http://tempuri.org/IPartidaManager/CrearPartidaResponse")]
        int CrearPartida(int idJugador, int idPalabra, string idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/CrearPartida", ReplyAction="http://tempuri.org/IPartidaManager/CrearPartidaResponse")]
        System.Threading.Tasks.Task<int> CrearPartidaAsync(int idJugador, int idPalabra, string idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerPartidasDisponiblesResponse")]
        AhorcadoCliente.ServiciosAhorcado.PartidaDisponibleDTO[] ObtenerPartidasDisponibles(int idJugadorActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.PartidaDisponibleDTO[]> ObtenerPartidasDisponiblesAsync(int idJugadorActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/UnirseAPartida", ReplyAction="http://tempuri.org/IPartidaManager/UnirseAPartidaResponse")]
        bool UnirseAPartida(int idPartida, int idJugador, string usernameInvitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/UnirseAPartida", ReplyAction="http://tempuri.org/IPartidaManager/UnirseAPartidaResponse")]
        System.Threading.Tasks.Task<bool> UnirseAPartidaAsync(int idPartida, int idJugador, string usernameInvitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/IntentarLetra", ReplyAction="http://tempuri.org/IPartidaManager/IntentarLetraResponse")]
        bool IntentarLetra(int idPartida, int idJugador, char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/IntentarLetra", ReplyAction="http://tempuri.org/IPartidaManager/IntentarLetraResponse")]
        System.Threading.Tasks.Task<bool> IntentarLetraAsync(int idPartida, int idJugador, char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerEstadoPalabra", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerEstadoPalabraResponse")]
        string ObtenerEstadoPalabra(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerEstadoPalabra", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerEstadoPalabraResponse")]
        System.Threading.Tasks.Task<string> ObtenerEstadoPalabraAsync(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerHistorialDeJugador", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerHistorialDeJugadorResponse")]
        AhorcadoCliente.ServiciosAhorcado.HistorialPartidaDTO[] ObtenerHistorialDeJugador(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerHistorialDeJugador", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerHistorialDeJugadorResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.HistorialPartidaDTO[]> ObtenerHistorialDeJugadorAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerDescripcionPalabra", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerDescripcionPalabraResponse")]
        string ObtenerDescripcionPalabra(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaManager/ObtenerDescripcionPalabra", ReplyAction="http://tempuri.org/IPartidaManager/ObtenerDescripcionPalabraResponse")]
        System.Threading.Tasks.Task<string> ObtenerDescripcionPalabraAsync(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorPrincipal/Ping", ReplyAction="http://tempuri.org/IGestorPrincipal/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorPrincipal/Ping", ReplyAction="http://tempuri.org/IGestorPrincipal/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestorPrincipalCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaManager/NotificarJugadorUnido")]
        void NotificarJugadorUnido(string usernameInvitado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaManager/NotificarIntentoLetra")]
        void NotificarIntentoLetra(char letra, bool acierto, string estadoActualPalabra);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaManager/NotificarFinPartida")]
        void NotificarFinPartida(bool gano, string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestorPrincipalChannel : AhorcadoCliente.ServiciosAhorcado.IGestorPrincipal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestorPrincipalClient : System.ServiceModel.DuplexClientBase<AhorcadoCliente.ServiciosAhorcado.IGestorPrincipal>, AhorcadoCliente.ServiciosAhorcado.IGestorPrincipal {
        
        public GestorPrincipalClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestorPrincipalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestorPrincipalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestorPrincipalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestorPrincipalClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int RegistrarJugador(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador) {
            return base.Channel.RegistrarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarJugadorAsync(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador) {
            return base.Channel.RegistrarJugadorAsync(jugador);
        }
        
        public int ActualizarJugador(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador) {
            return base.Channel.ActualizarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarJugadorAsync(AhorcadoCliente.ServiciosAhorcado.JugadorDTO jugador) {
            return base.Channel.ActualizarJugadorAsync(jugador);
        }
        
        public int EliminarJugador(int idJugador) {
            return base.Channel.EliminarJugador(idJugador);
        }
        
        public System.Threading.Tasks.Task<int> EliminarJugadorAsync(int idJugador) {
            return base.Channel.EliminarJugadorAsync(idJugador);
        }
        
        public AhorcadoCliente.ServiciosAhorcado.JugadorDTO[] ObtenerTodosLosJugadores() {
            return base.Channel.ObtenerTodosLosJugadores();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.JugadorDTO[]> ObtenerTodosLosJugadoresAsync() {
            return base.Channel.ObtenerTodosLosJugadoresAsync();
        }
        
        public AhorcadoCliente.ServiciosAhorcado.JugadorDTO IniciarSesion(string usuario, string contrasena) {
            return base.Channel.IniciarSesion(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.JugadorDTO> IniciarSesionAsync(string usuario, string contrasena) {
            return base.Channel.IniciarSesionAsync(usuario, contrasena);
        }
        
        public AhorcadoCliente.ServiciosAhorcado.CategoriaDTO[] ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.CategoriaDTO[]> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
        
        public AhorcadoCliente.ServiciosAhorcado.DificultadDTO[] ObtenerDificultades() {
            return base.Channel.ObtenerDificultades();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.DificultadDTO[]> ObtenerDificultadesAsync() {
            return base.Channel.ObtenerDificultadesAsync();
        }
        
        public AhorcadoCliente.ServiciosAhorcado.PalabraDTO[] ObtenerPalabrasPorCategoriaYDificultad(int idCategoria, int idDificultad) {
            return base.Channel.ObtenerPalabrasPorCategoriaYDificultad(idCategoria, idDificultad);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.PalabraDTO[]> ObtenerPalabrasPorCategoriaYDificultadAsync(int idCategoria, int idDificultad) {
            return base.Channel.ObtenerPalabrasPorCategoriaYDificultadAsync(idCategoria, idDificultad);
        }
        
        public int CrearPartida(int idJugador, int idPalabra, string idioma) {
            return base.Channel.CrearPartida(idJugador, idPalabra, idioma);
        }
        
        public System.Threading.Tasks.Task<int> CrearPartidaAsync(int idJugador, int idPalabra, string idioma) {
            return base.Channel.CrearPartidaAsync(idJugador, idPalabra, idioma);
        }
        
        public AhorcadoCliente.ServiciosAhorcado.PartidaDisponibleDTO[] ObtenerPartidasDisponibles(int idJugadorActual) {
            return base.Channel.ObtenerPartidasDisponibles(idJugadorActual);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.PartidaDisponibleDTO[]> ObtenerPartidasDisponiblesAsync(int idJugadorActual) {
            return base.Channel.ObtenerPartidasDisponiblesAsync(idJugadorActual);
        }
        
        public bool UnirseAPartida(int idPartida, int idJugador, string usernameInvitado) {
            return base.Channel.UnirseAPartida(idPartida, idJugador, usernameInvitado);
        }
        
        public System.Threading.Tasks.Task<bool> UnirseAPartidaAsync(int idPartida, int idJugador, string usernameInvitado) {
            return base.Channel.UnirseAPartidaAsync(idPartida, idJugador, usernameInvitado);
        }
        
        public bool IntentarLetra(int idPartida, int idJugador, char letra) {
            return base.Channel.IntentarLetra(idPartida, idJugador, letra);
        }
        
        public System.Threading.Tasks.Task<bool> IntentarLetraAsync(int idPartida, int idJugador, char letra) {
            return base.Channel.IntentarLetraAsync(idPartida, idJugador, letra);
        }
        
        public string ObtenerEstadoPalabra(int idPartida) {
            return base.Channel.ObtenerEstadoPalabra(idPartida);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEstadoPalabraAsync(int idPartida) {
            return base.Channel.ObtenerEstadoPalabraAsync(idPartida);
        }
        
        public AhorcadoCliente.ServiciosAhorcado.HistorialPartidaDTO[] ObtenerHistorialDeJugador(int idJugador) {
            return base.Channel.ObtenerHistorialDeJugador(idJugador);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiciosAhorcado.HistorialPartidaDTO[]> ObtenerHistorialDeJugadorAsync(int idJugador) {
            return base.Channel.ObtenerHistorialDeJugadorAsync(idJugador);
        }
        
        public string ObtenerDescripcionPalabra(int idPartida) {
            return base.Channel.ObtenerDescripcionPalabra(idPartida);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerDescripcionPalabraAsync(int idPartida) {
            return base.Channel.ObtenerDescripcionPalabraAsync(idPartida);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
